Audit fixes
Near-One/omni-bridge pull request #167
Opened 2024-12-25 09:42 UTC by kiseln

2024-12-25 14:07 UTC, olga24912 approved these changes

2024-12-25 16:22 UTC, frolvanya commented on evm/src/omni-bridge/contracts/OmniBridge.sol
> +        }
Wait, what about regular `fee`? I thought that we need to check it as well, but `valueRequired` doesn't consider it. Also, for Sepolia chains `messageFee` is `0`, but for other chains user might pay for it and then `msg.value` would be greater than a value calculated by `valueRequired`

2024-12-25 16:38 UTC, olga24912 commented on evm/src/omni-bridge/contracts/OmniBridge.sol
> +        }
fee refers to tokens, never Ether. valueRequired is a virtual function, and it’s calculated correctly.

2024-12-25 17:15 UTC, kiseln commented on evm/src/omni-bridge/contracts/OmniBridge.sol
> +        }
Ah so for wormhole it is already checked when sending a message? Then I'd probably just check for Ethereum version like you say

2024-12-26 15:30 UTC, kiseln commented on evm/src/omni-bridge/contracts/OmniBridge.sol
> +        }
Let's keep this perhaps in order not to rely on wormhole

2024-12-27 19:29 UTC, karim-en requested changes

2024-12-27 19:57 UTC, karim-en commented on evm/src/omni-bridge/contracts/OmniBridge.sol
> +        }
aa36c0049f6979538dd48f34d4e537e75b4925bd

2024-12-27 19:57 UTC, karim-en approved these changes

2024-12-30 14:11 UTC, olga24912 approved these changes

2024-12-30 14:21 UTC, merged