Add "Bridge New Token To Ethereum" workflow.
Near-One/omni-bridge pull request #170
Opened 2024-12-30 14:11 UTC by kisialiou

- Add contracts initialization.
- Add "Bridge New Token To Ethereum" workflow.

2025-01-13 18:53 UTC, olga24912 requested changes

2025-01-13 18:53 UTC, olga24912 commented on e2e-testing/Makefile
> +ethereum-deploy-token: $(EVM_DEPLOY_TOKEN_CALL_FILE)
Issue: 
https://testnet.nearblocks.io/txns/9axKcT1FiEF2aw97kkVeYBZ4ymajSSCnEJ7NTxpVQDGU#execution

The previous transaction failed and needs to be redone. However, this doesn't happen automatically, and the failure of the transaction isn't being checked. As a result, the error occurs at a later stage than it should.

It seems necessary to add a command like "clear everything and restart the test from scratch.

2025-01-14 11:04 UTC, kisialiou commented on e2e-testing/README.md
> +- **Private Key Requirement**: For Ethereum deployment, ensure that you add your `EVM_PRIVATE_KEY` to the `./evm/.env` file. This key is necessary for authenticating transactions on the Ethereum netw
1. We are using the same private key for all EVM chains, therefore it's called EVM_PRIVATE_KEY. In `bridge-sdk-config.example.json` I use the naming provided in the Bridge SDK and can't change it in this repo. I agree that it makes sense to change it to EVM_PRIVATE_KEY in Bridge SDK repo.
2. We are using the same private key for all EVM chains, including base and arbitrum.
3. ETH_RPC is required by Bridge SDK, not `evm_scripts`. I agree that configurations could be unified but I'd postpone it till later.
4. Agree.

2025-01-14 11:11 UTC, kisialiou commented on e2e-testing/Makefile
> +ethereum-deploy-token: $(EVM_DEPLOY_TOKEN_CALL_FILE)
Detecting the failure of the transaction (and moreover all of its receipts) on NEAR is not a straightforward task and is not supported in Bridge SDK. For now, I'd say that if the pipeline fails it's way easier to trace back the problematic place manually. Moreover, it tells us how far could the workflow go without detecting the failure.

However, it's a good point for the future. I've added it to the backlog.

2025-01-22 13:28 UTC, olga24912 approved these changes

2025-01-22 14:22 UTC, merged