Audit fixes #2
Near-One/omni-bridge pull request #171
Opened 2024-12-31 15:09 UTC by kiseln

Minor fixes for Solana. The biggest impact here is adding padding to the config account for easier extensibility in the future

https://github.com/AuditOneAuditReviews/Omnibridge2-audit-review/issues/11
https://github.com/AuditOneAuditReviews/Omnibridge2-audit-review/issues/12
https://github.com/AuditOneAuditReviews/Omnibridge2-audit-review/issues/13

2024-12-31 20:27 UTC, karim-en commented on solana/bridge_token_factory/programs/bridge_token_factory/src/instructions/user/finalize_transfer.rs
> +            &mut self.wormhole.config,
Using the config from Wormhole is a little bit confusing, can we pass it to the `post_message`?

2025-01-01 11:19 UTC, kiseln commented on solana/bridge_token_factory/programs/bridge_token_factory/src/instructions/user/finalize_transfer.rs
> +            &mut self.wormhole.config,
Should we rename wormhole to `common` or something like that?

2025-01-02 17:24 UTC, karim-en commented on solana/bridge_token_factory/programs/bridge_token_factory/src/instructions/user/finalize_transfer.rs
> +            &mut self.wormhole.config,
Yeah, this may work

2025-01-07 11:00 UTC, kiseln commented on solana/bridge_token_factory/programs/bridge_token_factory/src/instructions/user/finalize_transfer.rs
> +            &mut self.wormhole.config,
Renamed 90353fc40a9e9d5176bd11d49a602c9ea113d627

2025-01-07 11:27 UTC, olga24912 requested changes
It seems that only issue 11 has been addressed, while issues 9, 12, and 13 remain unchanged.

2025-01-07 11:27 UTC, olga24912 commented on solana/bridge_token_factory/programs/bridge_token_factory/src/instructions/user/init_transfer.rs
> +        owner = common.system_program.key(),
If I understood correctly, in issue 9, it is suggested to delete this line entirely as unnecessary.

https://github.com/AuditOneAuditReviews/Omnibridge2-audit-review/issues/9

2025-01-07 11:27 UTC, olga24912 commented on solana/bridge_token_factory/programs/bridge_token_factory/src/instructions/user/init_transfer_sol.rs
> +        owner = common.system_program.key(),
And remove this line as here (I am not expert in Solana, just read issue).

2025-01-07 11:27 UTC, olga24912 commented on solana/bridge_token_factory/programs/bridge_token_factory/src/state/config.rs
>      pub derived_near_bridge_address: [u8; 64],
According to issue 12, the value 64 should be defined as a constant.

2025-01-08 08:23 UTC, kiseln commented on solana/bridge_token_factory/programs/bridge_token_factory/src/state/config.rs
>      pub derived_near_bridge_address: [u8; 64],
I don't think it's necessary

2025-01-08 08:26 UTC, kiseln commented on solana/bridge_token_factory/programs/bridge_token_factory/src/instructions/user/init_transfer.rs
> +        owner = common.system_program.key(),
Ah, I think I referred to 9 by mistake. I did not intend to fix that one

2025-01-10 14:27 UTC, olga24912 approved these changes

2025-01-10 14:35 UTC, olga24912 approved these changes

2025-01-10 14:35 UTC, karim-en approved these changes

2025-01-10 14:36 UTC, merged